services:
  database:
    build: ./database
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: citasmedicas
      MYSQL_USER: admin
      MYSQL_PASSWORD: sistemas
      MYSQL_ROOT_PASSWORD: sistemas  # Contraseña para el usuario root
    volumes:
      - mysqldata:/var/lib/mysql  # Volumen para persistir datos
    ports: 
      - "3306:3306"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL = os.getenv('DATABASE_URL', 'mysql+pymysql://admin:sistemas@database/citasmedicas?charset=utf8mb4')
    ports:
      - "8000:8000"
    depends_on:
      - database


volumes:
  mysqldata: