services:
  database:
    build: ./database
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: citasmedicas
      MYSQL_USER: admin
      MYSQL_PASSWORD: sistemas
      MYSQL_ROOT_PASSWORD: sistemas  # Contraseña para el usuario root
    volumes:
      - mysqldata:/var/lib/mysql  # Volumen para persistir datos
    ports: 
      - "3306:3306"

volumes:
  mysqldata: